Добавлены домашние работы
netology-code/bjs-homeworks pull request #2
Opened 2018-11-07 20:25 UTC by vovachebr

2018-11-12 14:24 UTC, IvanBlacky requested changes
Все хорошо, но нужно немного поправить оформление

2018-11-12 14:24 UTC, IvanBlacky commented on 1.2 Extended syntax/task.js
> +function GetResult(a,b,c){
Название функции не бьется с тем, что было в тексте задания

2018-11-12 14:24 UTC, IvanBlacky commented on 1.2 Extended syntax/task.js
> +    //return x;
Здесь вывод закомментирован. В остальных функциях надо сделать также

2018-11-12 14:24 UTC, IvanBlacky commented on 1.2 Extended syntax/task.js
> +    //return x;
В функциях, которые должны быть изменены учеником лучше чтобы были комментарии об этом. Например,
```javascript
    // код для задачи №1 писать здесь:
    //return x;
```

2018-11-13 18:09 UTC, vovachebr commented on 1.2 Extended syntax/task.js
> +function GetResult(a,b,c){
Исправлено

2018-11-13 18:10 UTC, vovachebr commented on 1.2 Extended syntax/task.js
> +    //return x;
Исправлено

2018-11-13 19:53 UTC, IvanBlacky approved these changes
Все ок

2018-11-29 08:45 UTC, merged